#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  runtime/scripts/build_a3_app.sh [--jobs N] [--motion CSV] [--manifest JSON]
                                  [--dist DIRECTORY]

Builds the high-level A3 arm runner and binds it to one generated or validated
CSV plus its manifest.  The default artifact is the PR #18 validated serve.

Run this natively on the AArch64 MDU after sourcing the installed vendor ROS 2
environment. MuJoCo and IK run offboard before this build; no ONNX, RKNN,
TensorRT, planner, gripper, or low-level body-drive runner is packaged.
EOF
}

die() {
  echo "[build-serve-vendor-arm] ERROR: $*" >&2
  exit 1
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    die "sha256sum or shasum is required"
  fi
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
RUNTIME_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
APP_ROOT="$(cd -- "${RUNTIME_ROOT}/.." && pwd)"
SOURCE_DIR="${RUNTIME_ROOT}"
BUILD_DIR="${APP_ROOT}/build/a3_serve_vendor_arm"
DIST_DIR="${APP_ROOT}/dist/a3_serve_vendor_arm"
RUNNER="${BUILD_DIR}/out/a3_serve_vendor_arm_runner"
MOTION="${APP_ROOT}/assets/validated/serve_policy.csv"
MANIFEST="${APP_ROOT}/assets/validated/serve_vendor_arm.json"

if command -v nproc >/dev/null 2>&1; then
  JOBS="$(nproc)"
else
  JOBS=2
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    --jobs)
      JOBS="${2:-}"
      shift 2
      ;;
    --motion)
      MOTION="${2:-}"
      shift 2
      ;;
    --manifest)
      MANIFEST="${2:-}"
      shift 2
      ;;
    --dist)
      DIST_DIR="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
done

[[ "${JOBS}" =~ ^[1-9][0-9]*$ ]] ||
  die "--jobs must be a positive integer"
command -v cmake >/dev/null 2>&1 || die "cmake is required"
command -v install >/dev/null 2>&1 || die "install is required"
command -v python3 >/dev/null 2>&1 || die "python3 is required"
[[ -f "${MOTION}" ]] || die "serve CSV is missing: ${MOTION}"
[[ -f "${MANIFEST}" ]] || die "serve manifest is missing: ${MANIFEST}"
EXPECTED_MOTION_SHA256="$(
  python3 - "${MANIFEST}" <<'PY'
import json
import re
import sys

with open(sys.argv[1], encoding="utf-8") as stream:
    value = json.load(stream)["source"]["sha256"]
if not isinstance(value, str) or re.fullmatch(r"[0-9a-f]{64}", value) is None:
    raise SystemExit("manifest source.sha256 is not a lowercase SHA-256")
print(value)
PY
)" || die "cannot read source.sha256 from manifest"
[[ "$(sha256_file "${MOTION}")" == "${EXPECTED_MOTION_SHA256}" ]] ||
  die "serve CSV SHA does not match manifest source.sha256"

if [[ -f /agibot/software/v0/entry/env/env.sh ]]; then
  set +u
  # shellcheck disable=SC1091
  source /agibot/software/v0/entry/env/env.sh
  set -u
fi

cmake \
  -S "${SOURCE_DIR}" \
  -B "${BUILD_DIR}" \
  -DCMAKE_BUILD_TYPE=Release \
  -DSERVE_VENDOR_ARM_RUNTIME_OUTPUT_DIR="${BUILD_DIR}/out"
cmake --build "${BUILD_DIR}" --target a3_serve_vendor_arm_runner --parallel "${JOBS}"
[[ -x "${RUNNER}" ]] || die "runner was not built: ${RUNNER}"

cmake -E remove_directory "${DIST_DIR}"
mkdir -p "${DIST_DIR}/config" "${DIST_DIR}/motions"
install -m 0755 "${RUNNER}" "${DIST_DIR}/a3_serve_vendor_arm_runner"
install -m 0755 \
  "${SCRIPT_DIR}/run_a3_app.sh" \
  "${DIST_DIR}/run_a3_app.sh"
install -m 0755 \
  "${SCRIPT_DIR}/a3_app_common.sh" \
  "${DIST_DIR}/a3_app_common.sh"
install -m 0644 "${MOTION}" "${DIST_DIR}/motions/serve_policy.csv"
install -m 0644 \
  "${MANIFEST}" \
  "${DIST_DIR}/config/serve_vendor_arm_manifest.json"

SOURCE_GIT_SHA="unknown"
if git -C "${APP_ROOT}" rev-parse --verify HEAD >/dev/null 2>&1; then
  SOURCE_GIT_SHA="$(git -C "${APP_ROOT}" rev-parse HEAD)"
  if [[ -n "$(git -C "${APP_ROOT}" status --porcelain --untracked-files=normal -- .)" ]]; then
    SOURCE_GIT_SHA="${SOURCE_GIT_SHA}-dirty"
  fi
fi
cat >"${DIST_DIR}/config/serve_vendor_arm_build.env" <<EOF
# Generated by build_a3_app.sh.
SERVE_VENDOR_ARM_SOURCE_GIT_SHA=${SOURCE_GIT_SHA}
SERVE_VENDOR_ARM_BUILD_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)
SERVE_VENDOR_ARM_BUILD_MACHINE=$(uname -m)
SERVE_VENDOR_ARM_BINARY_SHA256=$(sha256_file "${DIST_DIR}/a3_serve_vendor_arm_runner")
SERVE_VENDOR_ARM_MOTION_SHA256=$(sha256_file "${DIST_DIR}/motions/serve_policy.csv")
EOF

PACKAGE_MANIFEST="${DIST_DIR}/config/serve_vendor_arm_package.sha256"
(
  cd "${DIST_DIR}"
  while IFS= read -r -d '' path; do
    relative="${path#./}"
    printf '%s  %s\n' "$(sha256_file "${relative}")" "${relative}"
  done < <(
    find . -type f \
      ! -path './config/serve_vendor_arm_package.sha256' \
      -print0 |
      LC_ALL=C sort -z
  )
) >"${PACKAGE_MANIFEST}"

while read -r expected relative || [[ -n "${expected}${relative}" ]]; do
  [[ "$(sha256_file "${DIST_DIR}/${relative}")" == "${expected}" ]] ||
    die "staged package SHA mismatch: ${relative}"
done <"${PACKAGE_MANIFEST}"

echo "[build-serve-vendor-arm] package: ${DIST_DIR}"
echo "[build-serve-vendor-arm] next: cd ${DIST_DIR} && ./run_a3_app.sh"
