#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/build_serve_vendor_arm_pkg.sh [--jobs N]

Builds only the fixed vendor motion-control arm runner and emits:
  dist/a3_serve_vendor_arm/

Run this natively on the AArch64 MDU after sourcing the installed vendor ROS 2
environment. No ONNX, RKNN, TensorRT, planner, gripper, low-level body-drive
runner, or policy target is configured or packaged.
EOF
}

die() {
  echo "[build-serve-vendor-arm] ERROR: $*" >&2
  exit 1
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    die "sha256sum or shasum is required"
  fi
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
A3_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
SOURCE_DIR="${A3_ROOT}/src/a3/a3_deploy_onnx_ref/serve_vendor_arm"
BUILD_DIR="${A3_ROOT}/build/a3_serve_vendor_arm"
DIST_DIR="${A3_ROOT}/dist/a3_serve_vendor_arm"
RUNNER="${BUILD_DIR}/out/a3_serve_vendor_arm_runner"
MOTION="${A3_ROOT}/assets/a3_runtime/serve/motions/serve_policy.csv"
MANIFEST="${A3_ROOT}/assets/a3_runtime/serve/manifests/serve_vendor_arm.json"
EXPECTED_MOTION_SHA256="2a7de3f1c97a300069899c139c9eb96e94fd61d3419701d5e44ef37b2bf6641d"

if command -v nproc >/dev/null 2>&1; then
  JOBS="$(nproc)"
else
  JOBS=2
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    --jobs)
      JOBS="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
done

[[ "${JOBS}" =~ ^[1-9][0-9]*$ ]] ||
  die "--jobs must be a positive integer"
command -v cmake >/dev/null 2>&1 || die "cmake is required"
command -v install >/dev/null 2>&1 || die "install is required"
[[ -f "${MOTION}" ]] || die "serve CSV is missing: ${MOTION}"
[[ -f "${MANIFEST}" ]] || die "serve manifest is missing: ${MANIFEST}"
[[ "$(sha256_file "${MOTION}")" == "${EXPECTED_MOTION_SHA256}" ]] ||
  die "serve CSV SHA does not match the committed manifest"

if [[ -f /agibot/software/v0/entry/env/env.sh ]]; then
  set +u
  # shellcheck disable=SC1091
  source /agibot/software/v0/entry/env/env.sh
  set -u
fi

cmake \
  -S "${SOURCE_DIR}" \
  -B "${BUILD_DIR}" \
  -DCMAKE_BUILD_TYPE=Release \
  -DSERVE_VENDOR_ARM_RUNTIME_OUTPUT_DIR="${BUILD_DIR}/out"
cmake --build "${BUILD_DIR}" --target a3_serve_vendor_arm_runner --parallel "${JOBS}"
[[ -x "${RUNNER}" ]] || die "runner was not built: ${RUNNER}"

cmake -E remove_directory "${DIST_DIR}"
mkdir -p "${DIST_DIR}/config" "${DIST_DIR}/motions"
install -m 0755 "${RUNNER}" "${DIST_DIR}/a3_serve_vendor_arm_runner"
install -m 0755 \
  "${SCRIPT_DIR}/run_serve_vendor_arm.sh" \
  "${DIST_DIR}/run_serve_vendor_arm.sh"
install -m 0755 \
  "${SCRIPT_DIR}/serve_vendor_arm_common.sh" \
  "${DIST_DIR}/serve_vendor_arm_common.sh"
install -m 0644 "${MOTION}" "${DIST_DIR}/motions/serve_policy.csv"
install -m 0644 \
  "${MANIFEST}" \
  "${DIST_DIR}/config/serve_vendor_arm_manifest.json"

SOURCE_GIT_SHA="unknown"
if git -C "${A3_ROOT}" rev-parse --verify HEAD >/dev/null 2>&1; then
  SOURCE_GIT_SHA="$(git -C "${A3_ROOT}" rev-parse HEAD)"
  if [[ -n "$(git -C "${A3_ROOT}" status --porcelain --untracked-files=normal -- .)" ]]; then
    SOURCE_GIT_SHA="${SOURCE_GIT_SHA}-dirty"
  fi
fi
cat >"${DIST_DIR}/config/serve_vendor_arm_build.env" <<EOF
# Generated by build_serve_vendor_arm_pkg.sh.
SERVE_VENDOR_ARM_SOURCE_GIT_SHA=${SOURCE_GIT_SHA}
SERVE_VENDOR_ARM_BUILD_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)
SERVE_VENDOR_ARM_BUILD_MACHINE=$(uname -m)
SERVE_VENDOR_ARM_BINARY_SHA256=$(sha256_file "${DIST_DIR}/a3_serve_vendor_arm_runner")
SERVE_VENDOR_ARM_MOTION_SHA256=$(sha256_file "${DIST_DIR}/motions/serve_policy.csv")
EOF

PACKAGE_MANIFEST="${DIST_DIR}/config/serve_vendor_arm_package.sha256"
(
  cd "${DIST_DIR}"
  while IFS= read -r -d '' path; do
    relative="${path#./}"
    printf '%s  %s\n' "$(sha256_file "${relative}")" "${relative}"
  done < <(
    find . -type f \
      ! -path './config/serve_vendor_arm_package.sha256' \
      -print0 |
      LC_ALL=C sort -z
  )
) >"${PACKAGE_MANIFEST}"

while read -r expected relative || [[ -n "${expected}${relative}" ]]; do
  [[ "$(sha256_file "${DIST_DIR}/${relative}")" == "${expected}" ]] ||
    die "staged package SHA mismatch: ${relative}"
done <"${PACKAGE_MANIFEST}"

echo "[build-serve-vendor-arm] package: ${DIST_DIR}"
echo "[build-serve-vendor-arm] next: cd ${DIST_DIR} && ./run_serve_vendor_arm.sh"
